language: java
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: XbbAAu11UJ9agWuQQiTK2mEXIkT1T8E1wgVywwuMvcogSAEphVxIK+a2BuaHUY6XXlfqjIRzilZ7CnlhKjCfao3OS5mk68DRgUhYE2fFGrDiyCcpVUrlfJcV8Yg+1JxOR69lS4bp6e0aDArWnbxy/7gQvdPoHyVAk+tQGT0n9/lQ1x7dYlSC9uOvZuuSFXwaQwygx6eZO10ENagfUELbdbkeb8booOPMkn9Eg1R9YlxED+OCV0pxHNpM7mBQ3+NOiPwt+grd/3B3E5NxIx5Qv1bDBNJZgUv8px/UEWQ+GQc9Wh4FEq+HKz2wLIPjbUrzJYZAcE+h4mxsA4D/jSdzLhaizRF6hdhhmQnBoigET7omWCKXdvF4cDbDk8hvnW8F9503NhDWhVnX3G2z//6SmsOqV9K1bhQONmXo5yeCXTUu/gX9ppuYBEHNQ/d5Gix/mhbkT2GcUGZwDNOmnTHu4lJV7QfzRUBdwp1ILsiP7Szxcnrl5D2LLApmlAK95CpjByW5nz8nVNYW1hjxRTgLJVJhLcIjfaOTI3/jHQA8uifoyzOE7roSlXMPCLK3cQHbKIYT5OKPIAktnrzUB+WHRAVQijpDCaxHWRelYAgNt7a+cEBoXYLzgj3r9LB9gDAss0+iM1y6VMURN7QX3cozvatxvq7StWuek8CaN6vCZ88=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-gateway-service
    branch: develop
