language: java
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: H0+BI8o8vVPaWzOcmb9itLQMkcn4x/YK6m+OMRFe1O2H0ZDEdHi0muKezgNROUZzorF+eqHMkhgQINK0z7kqSxSViCKInEEDT5CL8a9rA02wtSN4nHY6Sh5bL0svY9S4jSZAkN51057rv3A4jWVMTOGTKZIq8YoEj8oK05mENqCkEaUwDW1CDaocgrrqFeHELaxCor05UIQl+w90OvBp24eAKP0L7zZOVf+8TwidacXuNGbNmmqkUnvFCC2JM2WH3eyHCmELBAcLyFp/FyWj31DQOkc53NShJQPekwAjamFB2h+pD6NTV8wBw1vaWsQumYfAuUSiKnQYg5mz3wswh5SAm0hRDCwHiydulp2ZhQUUDHvkcg5ZA6oarvr0Nf/33BqqIhTHFsPpCIq9BN9gXAqb3/bU4Xd5PsLgknC8RrxguZFi7fM9LqFbq6G++5BYd//Pz5J10gT/Vsy0yS7UiuVB98FT++4WQvEp0Bj+kpwH3m7MAFJ273OSZa+a6aMAScLoRRdyAC4aXSs4O6aOPw0KL5K9Ut/P2IJJ+3CCfzNMcPZD9QeZKyFbZookZB767sCa1N0pNURmqRPuBA+spenU6XgAUwdhePiGo/eXKcrlVaAkCfq7NarLTWqLBnVDNTGQKKB11cDI6Dmh61Kz5nvbaNng/BFicDYUDBp7e+w=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-gateway-service
    branch: develop
