language: java
addons:
  sonarcloud:
    organization: hall-github
    token:
      secure: Sowb64c9iMACRf5//C6x0NsAVedC3aBerRjqOy7imT6xQattEYoM89nh7P4K5yBt0Xmw76RVj2W0OWwby/nnwqF89Bx7JnFUHIgxMhyE29eWTZ94O3CgF9KXC6mYFwpQtP6QzGwsjJbGEGBKz3fgkeUcSrJRBRvk2F8OO7yIo8Z/JffOZQzNRP+yab9HFP2ZWaoMPXnTrVzpVo/GtSBSoo649zBy+1Hgfv/hCOyxzPOtWUf0KL6egOnwbSvXSsMx21h1uTycjiqyDdxoWViDBf+npMZjZdJP+K6rtGJhh3j6WIml/7TsdO6rmdr4nIq/VqB85AvMpcwswWNj3s9wFv0mrI23DWhcf9WiySsE4ASnnCVcpkpzb7K53JXz9FupYKKa514HC+WgrhYrBDHYKgR+6G38IhuQE1nWNrd27l1Y5kfZ2cgebJNZJx8/tiMN3a5z2HLdqc/st16+yXnf45Ib/Q06zJOzsCDZHKjKxfH+igbvQD/opaAGhV4287v9GCt7MK9nbJZodEcGxXyCXxGPwvmfkgjE+HPD7PfdpN+r05jP+W9+Xr055Iz0VNtJXEyHrCCF1oePHyrpbs8p/V+h5q8M81ATcXg66GmVUaXGpYUeyrzKrRkD5k6aYAivOIPzqeQW771imW+4zP2YxqzfXi9Z8VZZWwjUXu2zrM4=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: G0+r5OVOATaGKAN8yeTFNLtjbfRDvtSwijRAU+L7+wDKKv55RfV17QUCiP2r6c0nAsy4qud0DyNGUOO33NUcxbjXEMsXndDcxcrOCte6G9Ysv9+8y9oTqM474ja72gYm3M3rczZ9sBccmpzh0RQvGWsAZI+ZAw0YbohuXhgULvZg6dL/gMKyOlHeDRA29R6Mk1tPD+apY3y+IFlXVxXIl/rDq+OZnlB3+ZqGsb9MHkvEkQ1I8FIQLBWxoDp2oGW6boN1NA3vNgl9yx64HahvCempo4ZzBEp9nCeGHCzDXfMurvcS1kzkjI7uxzrxaMQQ1ml2Iv0kp/UarpaOdgyS6JiQ9ydB6JZzwkRGaC5hmHmAVgo6jYLU0npSu1ZtQndalkANPo5kljqc7Ya58zfHUBmUrdSvDivHuUXnXtHSS3tIzyAXD5mpy/UGLNG5/VNZpYDtc5YvFKTmUDMBSmBSxsP881J6zzaR/4xUSpjDujej2veiHT0d+pEL0cF+mNXMYwyAzjtNqu66I1DsdJ0npSapBS9c7pZe1VPs3AYellLWG9eStr1yes4/eXq8fs0qzgFXpZUyuZ0CpIsn+3m19GmrXv8rqqDYD8jRXet67t5pT9ebgDIYAfMKt42DNL86hwTYb6KJx5ZpurQkOMSfLdjohMJ5Px9OuCbgMlsousQ=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-gateway-service
    branch: develop
