language: java
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: MB5LIiu9hLu7FBvyUMmiSp74TtlpamMxs0RcEvbJ9Y8H8CxCTnftH24ONm9Ov/7H36XXO7l+maokZBpkPW80Ldtls137k8m2LCHe62gOW5UKLRZTP9Y4DsWruS7OHKNCGb8wc6m+GSnpcrgamAovmYkP450avLWtwkSkLRxojIhtNXiOXFmUosXxJMGn1GFAgDdf/DwEQ6fBHIkcR6wLc5Aep0W5Pa6kxGaoXUknzaeqEkZ0hwTaXnOTNDMrGojld4j5dVj7vfsmrAEC7nHZaSh9ru4pmIOmdMpNIpVqnxFGAQm1y5SEA5sxJf5tg1ba4HDHM5P9GpG0WFuXwTsmhJ/53uW7LASiL+Ef8XSlrR3vlmVRkJWYTQYXVnI3WHX7OwmEp1/VGT/5EO4hKHRMumd7yuDJ1qtTb+xFhMeP2ME3S3pgmeAuMoHzr1cET2bEhdlLieMhdI3ctxReg6Ur6OMc7E5mT+dTIUyw6idYm0bTl+Bh03W+tNlNp+zLQzmUnNncK400H4tY1McywE3ngbQh4YCoWHdxBUu4365+TqxfGRfsVJ0tL0ipU3dqD+Qf7ehVEGrHo2e+85I6A88n9cLn7FbgWSXyn+/XzTqa6UzMoJf49k+7Jf5DDOU4djZw4A2o+LMvWU/r0PLIpZKhptI7lzohn96ujeMoLqFLOG0=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-gateway-service
    branch: develop
