spring:
  application:
    name: gateway
  cloud:
    services:
      registrationMethod: direct

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

zuul:
  prefix: /api
  routes:
    aggregator:
      path: /**
      serviceId: aggregator
    # address:
    #   path: /address/**
    #   serviceId: address
    # batch:
    #   path: /batch/**
    #   serviceId: batch
    # curriculum:
    #   path: /curriculum/**
    #   serviceId: curriculum
    # skills:
    #   path: /skills/**
    #   serviceId: skills
    # trainer:
    #   path: /trainer/**
    #   serviceId: trainer
    # unavailable:
    #   path: /unavailable/**
    #   serviceId: unavailable
    endpoints:
      routes:
        enabled: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
