spring:
  application:
    name: gateway
  cloud:
    services:
      registrationMethod: direct

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

zuul:
  prefix: /api
  routes:
    batch:
      path: /batch/**
      serviceId: batch
    curriculum:
      path: /curriculum/**
      serviceId: curriculum
    address:
      path: /address/**
      serviceId: address
    endpoints:
      routes:
        enabled: true
